ERROR 2025-08-28 19:12:11,005 exception 3488 140088718161728 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-08-28 19:12:11,005 exception 3488 140088718161728 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/krstevski/.pyenv/versions/3.11.5/lib/python3.11/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:03,974 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:03,974 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:04,150 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:04,150 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:05,701 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:05,701 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:06,007 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:06,007 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:11,845 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:11,845 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:11,980 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:11,980 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:14,404 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:14,404 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:14,536 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:14,536 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,172 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,172 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,271 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,271 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,418 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:17,418 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:25,927 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:25,927 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:26,071 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:26,071 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,025 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,025 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,438 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,438 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,573 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-08-31 21:18:30,573 log 3265072 139687940684096 Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'autodinero.krstevski.me'. You may need to add 'autodinero.krstevski.me' to ALLOWED_HOSTS.
ERROR 2025-09-01 19:32:48,465 log 348883 139687940684096 Internal Server Error: /en/vehicles/3/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'custom_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 148, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'custom_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
ERROR 2025-09-01 19:59:27,360 log 373764 139687940684096 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'number_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 51, in admin_dashboard
    return render(request, "admin_custom/dashboard.html", {
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'number_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
ERROR 2025-09-01 19:59:53,151 log 373812 139687940684096 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'number_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 51, in admin_dashboard
    return render(request, "admin_custom/dashboard.html", {
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'number_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
ERROR 2025-09-01 19:59:59,386 log 373812 139687940684096 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'number_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 51, in admin_dashboard
    return render(request, "admin_custom/dashboard.html", {
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'number_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
ERROR 2025-09-01 20:00:22,098 log 374652 139687940684096 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'number_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 51, in admin_dashboard
    return render(request, "admin_custom/dashboard.html", {
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'number_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
ERROR 2025-09-01 20:00:30,114 log 374652 139687940684096 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'number_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 51, in admin_dashboard
    return render(request, "admin_custom/dashboard.html", {
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'number_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
ERROR 2025-09-02 06:56:03,331 log 1009459 139687940684096 Internal Server Error: /dashboard/cars/add/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 140, in admin_car_add
    is_valid = car_form.is_valid()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 249, in clean
    total_size = self.get_total_size()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 238, in get_total_size
    for img in self.images.all():
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 164, in all
    return self.get_queryset()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
    raise ValueError(
ValueError: 'Car' instance needs to have a primary key value before this relationship can be used.
ERROR 2025-09-02 06:56:38,522 log 1009606 139687940684096 Internal Server Error: /dashboard/cars/add/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 140, in admin_car_add
    is_valid = car_form.is_valid()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 249, in clean
    total_size = self.get_total_size()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 238, in get_total_size
    for img in self.images.all():
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 164, in all
    return self.get_queryset()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
    raise ValueError(
ValueError: 'Car' instance needs to have a primary key value before this relationship can be used.
ERROR 2025-09-02 07:04:10,192 log 1017889 139687940684096 Internal Server Error: /dashboard/cars/add/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/views.py", line 140, in admin_car_add
    is_valid = car_form.is_valid()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/forms.py", line 435, in full_clean
    self._post_clean()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/forms/models.py", line 486, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/base.py", line 1477, in full_clean
    self.clean()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 249, in clean
    total_size = self.get_total_size()
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/models.py", line 238, in get_total_size
    for img in self.images.all():
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/manager.py", line 164, in all
    return self.get_queryset()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
    raise ValueError(
ValueError: 'Car' instance needs to have a primary key value before this relationship can be used.
ERROR 2025-09-04 18:30:59,173 log 6239 139767939155776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-09-04 18:30:59,173 log 6239 139767939155776 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
ERROR 2025-09-07 13:45:18,286 log 223152 139687940684096 Internal Server Error: /en/collaboration/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 250, in collaboration
    return render(request, 'frontend/collaboration.html')
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: frontend/collaboration.html
ERROR 2025-09-13 18:31:29,115 log 2124981 139687940684096 Internal Server Error: /en/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/middleware.py", line 101, in __call__
    language_from_session = request.session.get(translation.LANGUAGE_SESSION_KEY)
AttributeError: module 'django.utils.translation' has no attribute 'LANGUAGE_SESSION_KEY'
ERROR 2025-09-13 20:09:12,451 log 2250000 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:13,855 log 2250000 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:38,071 log 2250226 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:38,803 log 2250226 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:39,943 log 2250226 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:47,940 log 2250226 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:50,737 log 2250226 139687940684096 Internal Server Error: /en/vehicles/6/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:54,515 log 2250226 139687940684096 Internal Server Error: /en/vehicles/25/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:55,778 log 2250226 139687940684096 Internal Server Error: /en/vehicles/24/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:56,702 log 2250226 139687940684096 Internal Server Error: /en/vehicles/23/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:57,621 log 2250226 139687940684096 Internal Server Error: /en/vehicles/22/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:58,456 log 2250226 139687940684096 Internal Server Error: /en/vehicles/21/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:09:59,283 log 2250226 139687940684096 Internal Server Error: /en/vehicles/20/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:10:00,148 log 2250226 139687940684096 Internal Server Error: /en/vehicles/6/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:10:02,329 log 2250226 139687940684096 Internal Server Error: /en/vehicles/7/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI DSG>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
ERROR 2025-09-13 20:10:20,427 log 2251271 139687940684096 Internal Server Error: /en/vehicles/23/
Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'remaining_slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/krstevski/domains/autodinero.krstevski.me/public_html/dealership_app/frontend_views.py", line 160, in vehicle_detail
    return render(request, 'frontend/vehicle_detail.html', context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/defaulttags.py", line 189, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/krstevski/.local/lib/python3.9/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [remaining_slots] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'car': <Car: VW Golf 7 2.0 TDI R-Line (Copy 4)>, 'recommended_cars': [<Car: VW Golf 7 2.0 TDI R-Line (Copy 6)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 5)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 3)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy 2)>, <Car: VW Golf 7 2.0 TDI R-Line (Copy)>, <Car: VW Golf 7 2.0 TDI R-Line>, <Car: VW Golf 7 2.0 TDI DSG>], 'current_language': 'en', 'LANGUAGE_CODE': 'en', 'LANGUAGES': [('en', 'English'), ('mk', 'Македонски')], 'languages': [{'bidi': False, 'code': 'en', 'name': 'English', 'name_local': 'English', 'name_translated': 'English'}, {'bidi': False, 'code': 'mk', 'name': 'Macedonian', 'name_local': 'Македонски', 'name_translated': 'Macedonian'}]}]
